const REPO='nirav2000/Apps';const SEARCH_API='https://api.github.com/search/issues?q=user%3Anirav2000+is%3Aissue+is%3Aopen&per_page=100&page=';const cardsEl=document.querySelector('#cards');const emptyEl=document.querySelector('#empty');const statusEl=document.querySelector('#loadStatus');const template=document.querySelector('#cardTemplate');const search=document.querySelector('#search');let items=[];let currentView='needs-me';

const clean=s=>(s||'').replace(/\r/g,'').trim();
function section(body,names){for(const name of names){const rx=new RegExp('(?:^|\\n)#{1,4}\\s*'+name+'\\s*\\n([\\s\\S]*?)(?=\\n#{1,4}\\s|$)','i');const m=body.match(rx);if(m)return clean(m[1]).replace(/^[-*]\s*/gm,'');}return''}
function lineValue(body,labels){for(const label of labels){const rx=new RegExp('(?:^|\\n)(?:[-*]\\s*)?\\*{0,2}'+label+'\\*{0,2}\\s*:\s*(.+)','i');const m=body.match(rx);if(m)return clean(m[1]).replace(/\*\*/g,'');}return''}
function firstParagraph(body){return clean(body).replace(/^#+.*$/gm,'').split(/\n\s*\n/).map(clean).find(Boolean)||''}
function urlFrom(text){const m=(text||'').match(/https?:\/\/[^\s)>]+/);return m?m[0]:''}
function parse(issue){const b=issue.body||'';const what=section(b,['What is this\\?','Goal','Summary'])||firstParagraph(b)||issue.title;const why=section(b,['Why do I care\\?','Why it matters','Rationale'])||lineValue(b,['Why it matters','Why'])||'Context is captured in the issue; no separate impact statement has been added yet.';const next=section(b,['What happens next\\?','Next action','Acceptance'])||lineValue(b,['Next action'])||'Review the issue and determine the next concrete action.';const who=section(b,['Who needs to act\\?','Who needs to act','Owner'])||lineValue(b,['Who needs to act','Owner'])||'ChatGPT / development';const source=section(b,['Source / context','Source context'])||lineValue(b,['Source context','Source'])||'GitHub issue / development tracker';const sourceUrl=lineValue(b,['Source chat URL','Source URL'])||((/chatgpt\.com\//i.test(source))?urlFrom(source):'');const due=lineValue(b,['Due','Target date','Due date']);const status=lineValue(b,['Status']);const app=lineValue(b,['App','Repository'])||REPO;const labels=(issue.labels||[]).map(l=>typeof l==='string'?l:l.name).filter(Boolean);const lower=(b+' '+labels.join(' ')+' '+who+' '+status).toLowerCase();const needsMe=/needs me|who needs to act[^\n]*user|\buser\b.*(?:test|verify|choose|approve|provide|visit|check)/i.test(b)||labels.some(l=>/needs[- ]?me/i.test(l));return{issue,what,why,next,who,source,sourceUrl,due,status,app,labels,needsMe,lower}}
function dateInfo(due){if(!due)return{today:false,overdue:false};const d=new Date(due+'T23:59:59');if(Number.isNaN(d.getTime()))return{today:false,overdue:false};const now=new Date();const a=new Date(now.getFullYear(),now.getMonth(),now.getDate());const b=new Date(d.getFullYear(),d.getMonth(),d.getDate());return{today:+a===+b,overdue:b<a}}
function matchView(i){const s=(i.status+' '+i.lower).toLowerCase();const di=dateInfo(i.due);if(currentView==='all')return true;if(currentView==='needs-me')return i.needsMe;if(currentView==='today')return di.today||di.overdue;if(currentView==='next')return /\bnext\b/.test(s);if(currentView==='in-progress')return /in progress|doing/.test(s);if(currentView==='verify')return /verify|verification|test/.test(s);if(currentView==='waiting')return /waiting|blocked/.test(s);if(currentView==='explore')return /explore|research|investigat/.test(s);return true}
function setView(view){currentView=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={'needs-me':['YOUR ACTIONS','Needs me'],today:['TIME-SENSITIVE','Today / overdue'],next:['UP NEXT','Next'], 'in-progress':['ACTIVE','In progress'],verify:['CHECK','Verify'],waiting:['DEPENDENCIES','Waiting'],explore:['DISCOVER','Explore'],all:['ALL WORK','Open development work']};document.querySelector('#viewEyebrow').textContent=names[view][0];document.querySelector('#viewTitle').textContent=names[view][1];render()}
async function copyCommand(command,button){try{await navigator.clipboard.writeText(command);const old=button.textContent;button.textContent='Copied';setTimeout(()=>button.textContent=old,1400)}catch{window.prompt('Copy this into ChatGPT:',command)}}
function actionButton(label,command,className='action-button'){const b=document.createElement('button');b.type='button';b.className=className;b.textContent=label;b.addEventListener('click',()=>copyCommand(command,b));return b}
function trackerCommand(i,action){const repo=i.issue._repo||repoFromIssue(i.issue);const ref=repo+'#'+i.issue.number;return '#dev '+action+' — '+i.issue.title+' ['+ref+']'}
function snoozeCommand(i){const when=window.prompt('Snooze until when?','tomorrow');if(!when)return'';return trackerCommand(i,'snooze until '+when)}
function render(){const q=search.value.trim().toLowerCase();const visible=items.filter(matchView).filter(i=>!q||JSON.stringify(i).toLowerCase().includes(q));cardsEl.innerHTML='';emptyEl.hidden=visible.length>0;for(const i of visible){const n=template.content.cloneNode(true);n.querySelector('.card-title').textContent=i.issue.title;n.querySelector('.what').textContent=i.what;n.querySelector('.why').textContent=i.why;n.querySelector('.next').textContent=i.next;n.querySelector('.who').textContent=i.who;n.querySelector('.source').textContent=i.source;const num=n.querySelector('.issue-number');num.textContent='#'+i.issue.number;num.href=i.issue.html_url;const pills=n.querySelector('.pills');if(i.needsMe)pills.insertAdjacentHTML('beforeend','<span class="pill needs">Needs me</span>');if(i.status)pills.insertAdjacentHTML('beforeend','<span class="pill">'+i.status+'</span>');if(i.due){const di=dateInfo(i.due);pills.insertAdjacentHTML('beforeend','<span class="pill '+((di.today||di.overdue)?'due':'')+'">'+(di.overdue?'Overdue · ':di.today?'Today · ':'')+i.due+'</span>')}if(i.app)pills.insertAdjacentHTML('beforeend','<span class="pill">'+i.app+'</span>');const sl=n.querySelector('.source-link');if(i.sourceUrl){sl.href=i.sourceUrl;sl.hidden=false}const actions=n.querySelector('.card-actions');const urls=[...new Set((i.issue.body||'').match(/https?:\/\/[^\s)>]+/g)||[])].filter(u=>u!==i.sourceUrl&&u!==i.issue.html_url).slice(0,4);urls.forEach((u,idx)=>{const a=document.createElement('a');a.href=u;a.target='_blank';a.rel='noopener';a.className='action-link';a.textContent=idx===0?'Open related link':'Related link '+(idx+1);actions.appendChild(a)});
actions.appendChild(actionButton('Done',trackerCommand(i,'mark done')));
actions.appendChild(actionButton('Verified',trackerCommand(i,'mark verified')));
const snooze=actionButton('Snooze','');snooze.addEventListener('click',()=>{const cmd=snoozeCommand(i);if(cmd)copyCommand(cmd,snooze)},{once:false});actions.appendChild(snooze);
const ask=actionButton('Continue in ChatGPT',trackerCommand(i,'continue this item with the current context'),'action-button primary-action');actions.appendChild(ask);
cardsEl.appendChild(n)}}
function updateCounts(){document.querySelector('#openCount').textContent=items.length;document.querySelector('#needsMeCount').textContent=items.filter(i=>i.needsMe).length;document.querySelector('#todayCount').textContent=items.filter(i=>{const d=dateInfo(i.due);return d.today||d.overdue}).length}
function repoFromIssue(issue){const u=issue.repository_url||'';const m=u.match(/\/repos\/([^/]+\/[^/]+)$/);return m?m[1]:REPO}
async function fetchAllOpenIssues(){const all=[];for(let page=1;page<=10;page++){const r=await fetch(SEARCH_API+page,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error('GitHub returned '+r.status);const data=await r.json();const batch=data.items||[];all.push(...batch);if(batch.length<100)break}return all}
async function load(){try{const raw=await fetchAllOpenIssues();items=raw.filter(x=>!x.pull_request).map(issue=>{issue._repo=repoFromIssue(issue);return parse(issue)});items.forEach(i=>{if(!lineValue(i.issue.body||'',['App','Repository']))i.app=i.issue._repo||REPO});updateCounts();statusEl.textContent='Live across GitHub repositories · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});render()}catch(e){statusEl.textContent='Could not refresh issues: '+e.message;statusEl.style.color='var(--red)'}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));search.addEventListener('input',render);document.querySelector('#copyDev').addEventListener('click',async()=>{const t=document.querySelector('#captureText').value.trim();if(!t)return;const value=t.startsWith('#dev')?t:'#dev '+t;try{await navigator.clipboard.writeText(value);document.querySelector('#copyStatus').textContent='Copied — paste into any ChatGPT chat.'}catch{document.querySelector('#copyStatus').textContent=value}});
load();