import { Auth } from './index.js';

const CSS = [
':host{--auth-bg:#fff;--auth-fg:#182235;--auth-muted:#687386;--auth-border:#d8dee7;--auth-accent:#245edb;--auth-accent-2:#3478f6;--auth-soft:#f5f8fd;--auth-danger:#b42318;display:block;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text",Inter,system-ui,sans-serif;color:var(--auth-fg)}',
'*{box-sizing:border-box}button,input{font:inherit}.panel{width:min(100%,430px);margin:auto;background:var(--auth-bg);border:1px solid var(--auth-border);border-radius:24px;padding:24px;box-shadow:0 18px 55px rgba(28,42,70,.09)}',
'.head{margin-bottom:20px}h2{font-size:28px;line-height:1.08;margin:0 0 8px;letter-spacing:-.035em}.sub{margin:0;color:var(--auth-muted);font-size:14px;line-height:1.45}.center{text-align:center}.center .sub{max-width:310px;margin:auto}',
'.feature{width:62px;height:62px;border-radius:20px;margin:0 auto 18px;display:grid;place-items:center;background:linear-gradient(145deg,#eef4ff,#f8fbff);border:1px solid #dae5f5;color:var(--auth-accent);font-size:27px}',
'.stack{display:grid;gap:11px}.field{position:relative}.field .ico{position:absolute;left:14px;top:50%;transform:translateY(-50%);color:#718097;font-size:16px}.field input{width:100%;border:1px solid var(--auth-border);background:#fff;color:var(--auth-fg);border-radius:13px;padding:13px 14px 13px 42px;outline:none}.field input:focus{border-color:var(--auth-accent);box-shadow:0 0 0 3px rgba(36,94,219,.12)}',
'.primary,.secondary,.provider,.text-btn,.guest-card{cursor:pointer}.primary{width:100%;border:0;border-radius:13px;padding:13px 16px;background:linear-gradient(135deg,var(--auth-accent),var(--auth-accent-2));color:#fff;font-weight:750;box-shadow:0 8px 18px rgba(36,94,219,.18)}',
'.secondary{border:1px solid var(--auth-border);background:#fff;color:var(--auth-fg);border-radius:12px;padding:11px 13px;font-weight:650}.divider{display:flex;align-items:center;gap:12px;color:#8792a3;font-size:12px;margin:15px 0}.divider:before,.divider:after{content:"";height:1px;background:#e4e8ee;flex:1}',
'.providers{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.provider{border:1px solid var(--auth-border);background:#fff;border-radius:12px;padding:11px 8px;color:var(--auth-fg);font-weight:650;min-height:44px;display:flex;align-items:center;justify-content:center;gap:7px}.provider svg{flex:none}.links{display:flex;justify-content:center;gap:8px 14px;flex-wrap:wrap;margin-top:14px}.text-btn{border:0;background:none;padding:2px;color:var(--auth-accent);font-size:12px}',
'.guest-card{width:100%;margin-top:15px;border:1px solid #e0e7f1;background:linear-gradient(135deg,#f5f8fe,#fbfdff);border-radius:14px;padding:12px 14px;display:flex;align-items:center;gap:11px;text-align:left;color:var(--auth-fg)}.guest-icon{width:35px;height:35px;border-radius:11px;background:#e7efff;color:var(--auth-accent);display:grid;place-items:center;flex:none}.guest-card b{display:block;font-size:13px}.guest-card small{display:block;color:var(--auth-muted);font-size:11px;margin-top:2px}',
'.status{display:block;min-height:18px;margin-top:10px;font-size:12px;color:var(--auth-muted)}.status.error{color:var(--auth-danger)}.mode-switch{display:flex;background:#f4f6f9;border-radius:12px;padding:3px;margin-bottom:16px}.mode-switch button{flex:1;border:0;background:transparent;border-radius:9px;padding:8px;color:var(--auth-muted);font-weight:650}.mode-switch button.active{background:#fff;color:var(--auth-fg);box-shadow:0 1px 4px rgba(20,35,60,.09)}',
'.alt-list{display:grid;gap:8px;margin-top:12px}.alt-list .secondary{width:100%}.magic-note{text-align:center;color:var(--auth-muted);font-size:11px;margin-top:10px}.benefits{display:grid;gap:8px;margin:18px 0 2px}.benefit{display:flex;gap:8px;color:var(--auth-muted);font-size:12px}.tick{color:#19a060;font-weight:900}.more{border-top:1px solid #edf0f4;margin-top:14px;padding-top:12px}.more summary{cursor:pointer;color:var(--auth-accent);font-size:12px;text-align:center;list-style:none}.more summary::-webkit-details-marker{display:none}',
'.compact.panel{padding:18px;border-radius:18px;max-width:390px}.compact h2{font-size:22px}.compact .head{margin-bottom:14px}.compact .providers{grid-template-columns:repeat(3,1fr)}',
'.classic-panel{max-width:420px;padding:18px;border-radius:16px;box-shadow:none}.classic-panel .classic-title{font-size:18px;margin:0 0 12px}.classic-panel .classic-row{display:grid;gap:10px}.classic-panel .classic-input{width:100%;border:1px solid var(--auth-border);border-radius:10px;padding:10px 12px}.classic-panel .classic-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.classic-panel .classic-primary{border:0;background:var(--auth-accent);color:#fff;border-radius:10px;padding:10px 12px}.classic-panel .classic-secondary{background:transparent;color:var(--auth-fg);border:1px solid var(--auth-border);border-radius:10px;padding:10px 12px;display:inline-flex;align-items:center;gap:6px}.classic-panel .classic-secondary svg{flex:none}',
'.identity{display:flex;gap:12px;align-items:center}.avatar{width:44px;height:44px;border-radius:50%;background:linear-gradient(135deg,#dfe9ff,#f2f6ff);display:grid;place-items:center;color:var(--auth-accent);font-weight:800}.identity small{display:block;color:var(--auth-muted);margin-top:3px}.signed-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}',
':host([theme="airy"]){--auth-bg:#fff;--auth-fg:#182235;--auth-muted:#687386;--auth-border:#d8dee7;--auth-accent:#245edb;--auth-accent-2:#3478f6;--auth-soft:#f5f8fd}.panel{transition:background .2s,border-color .2s,color .2s,box-shadow .2s}',
':host([theme="glass"]){--auth-bg:rgba(255,255,255,.78);--auth-fg:#122038;--auth-muted:#617086;--auth-border:rgba(255,255,255,.72);--auth-accent:#3769e8;--auth-accent-2:#62a0ff;--auth-soft:rgba(242,247,255,.66)}:host([theme="glass"]) .panel{backdrop-filter:blur(22px) saturate(145%);box-shadow:0 24px 70px rgba(31,52,88,.18),inset 0 1px 0 rgba(255,255,255,.7)}',
':host([theme="warm"]){--auth-bg:#fffaf2;--auth-fg:#2c261f;--auth-muted:#786d60;--auth-border:#e8ddcf;--auth-accent:#b85d36;--auth-accent-2:#db8357;--auth-soft:#fff2e4}:host([theme="warm"]) .panel{box-shadow:0 18px 48px rgba(111,72,42,.12)}',
':host([theme="midnight"]){--auth-bg:#121a29;--auth-fg:#f4f7fb;--auth-muted:#a8b4c7;--auth-border:#2d3b50;--auth-accent:#6c8cff;--auth-accent-2:#8b6cff;--auth-soft:#1a2537}:host([theme="midnight"]) .panel{box-shadow:0 24px 70px rgba(5,10,20,.4)}:host([theme="midnight"]) input,:host([theme="midnight"]) .provider,:host([theme="midnight"]) .secondary,:host([theme="midnight"]) .classic-input,:host([theme="midnight"]) .classic-secondary{background:#172235;color:var(--auth-fg);border-color:#344359}:host([theme="midnight"]) .mode-switch{background:#192436}:host([theme="midnight"]) .mode-switch button.active{background:#26344a;color:#fff}:host([theme="midnight"]) .guest-card{background:#172235;border-color:#344359}',
':host([theme="playful"]){--auth-bg:#fff;--auth-fg:#20213d;--auth-muted:#706d88;--auth-border:#dedcf0;--auth-accent:#6557d9;--auth-accent-2:#2fb7a4;--auth-soft:#f4f1ff}:host([theme="playful"]) .panel{box-shadow:0 20px 60px rgba(86,72,180,.15)}:host([theme="playful"]) .feature,:host([theme="playful"]) .guest-icon{background:linear-gradient(145deg,#efeaff,#e5fbf7)}',
':host([theme="aurora-glass"]){--auth-bg:rgba(229,235,255,.70);--auth-fg:#f9fbff;--auth-muted:#d3daed;--auth-border:rgba(255,255,255,.38);--auth-accent:#8f7cff;--auth-accent-2:#5c9bff;--auth-soft:rgba(255,255,255,.12)}:host([theme="aurora-glass"]) .panel{position:relative;overflow:hidden;background:radial-gradient(circle at 15% 8%,rgba(102,146,255,.55),transparent 34%),radial-gradient(circle at 88% 18%,rgba(255,171,198,.48),transparent 35%),linear-gradient(145deg,rgba(61,76,122,.88),rgba(164,139,169,.76));border:1px solid rgba(255,255,255,.46);backdrop-filter:blur(26px) saturate(145%);box-shadow:0 28px 80px rgba(26,37,68,.34),inset 0 1px 0 rgba(255,255,255,.55)}:host([theme="aurora-glass"]) .panel:before{content:"";position:absolute;inset:-35% -20% auto;height:190px;background:radial-gradient(circle,rgba(255,255,255,.24),transparent 62%);filter:blur(10px);pointer-events:none}:host([theme="aurora-glass"]) .panel>*{position:relative}:host([theme="aurora-glass"]) h2{font-family:Georgia,"Times New Roman",serif;font-weight:650;letter-spacing:-.04em}:host([theme="aurora-glass"]) .providers{grid-template-columns:1fr}:host([theme="aurora-glass"]) .provider,:host([theme="aurora-glass"]) .secondary,:host([theme="aurora-glass"]) .field input,:host([theme="aurora-glass"]) .classic-input,:host([theme="aurora-glass"]) .classic-secondary{background:rgba(255,255,255,.86);color:#182235;border-color:rgba(255,255,255,.62);box-shadow:0 8px 18px rgba(35,43,72,.10)}:host([theme="aurora-glass"]) .provider{justify-content:flex-start;padding:13px 17px}:host([theme="aurora-glass"]) .provider[data-apple]{background:#0d0e12;color:#fff;border-color:#0d0e12}:host([theme="aurora-glass"]) .primary{background:linear-gradient(135deg,#8f7cff,#5c9bff);box-shadow:0 10px 28px rgba(74,87,189,.32)}:host([theme="aurora-glass"]) .divider{color:#e5e9f6}:host([theme="aurora-glass"]) .divider:before,:host([theme="aurora-glass"]) .divider:after{background:rgba(255,255,255,.34)}:host([theme="aurora-glass"]) .text-btn{color:#f4f6ff}:host([theme="aurora-glass"]) .guest-card{background:rgba(255,255,255,.12);border-color:rgba(255,255,255,.25);color:#fff}:host([theme="aurora-glass"]) .guest-card small{color:#d5dced}',
':host([theme="editorial"]){--auth-bg:#fffaf2;--auth-fg:#241f1a;--auth-muted:#75685b;--auth-border:#eadfd1;--auth-accent:#a96d34;--auth-accent-2:#d59a55;--auth-soft:#fff3e4}:host([theme="editorial"]) .panel{position:relative;overflow:hidden;padding-top:132px;background:linear-gradient(180deg,#fffdf8,#fff8ee);border-color:#e7d8c6;box-shadow:0 28px 70px rgba(100,69,42,.20)}:host([theme="editorial"]) .panel:before{content:"";position:absolute;left:0;right:0;top:0;height:105px;background:radial-gradient(circle at 76% 32%,#f0c276 0 9%,transparent 10%),radial-gradient(ellipse at 83% 78%,#8ca18c 0 18%,transparent 19%),linear-gradient(135deg,#d7aa79 0 24%,#f2dcc3 24% 58%,#b9c7b3 58% 74%,#d8b383 74%);opacity:.82}:host([theme="editorial"]) .panel:after{content:"";position:absolute;top:78px;left:-10%;width:120%;height:58px;border-radius:50% 50% 0 0/100% 100% 0 0;background:#fffaf2}:host([theme="editorial"]) .panel>*{position:relative;z-index:1}:host([theme="editorial"]) h2{font-family:Georgia,"Times New Roman",serif;font-size:34px;font-weight:500;letter-spacing:-.035em;text-align:center}:host([theme="editorial"]) .head .sub{text-align:center}:host([theme="editorial"]) .providers{grid-template-columns:1fr}:host([theme="editorial"]) .provider{justify-content:flex-start;padding:13px 17px;background:#fff;border-color:#eadfd3;box-shadow:0 6px 16px rgba(102,73,45,.08)}:host([theme="editorial"]) .provider[data-apple]{background:#25221e;color:#fff;border-color:#25221e}:host([theme="editorial"]) .primary{background:linear-gradient(135deg,#9f682e,#c98c48);box-shadow:0 10px 24px rgba(158,102,45,.25)}:host([theme="editorial"]) .feature{background:#f5e4cc;border-color:#ead3b6;color:#956235}:host([theme="editorial"]) .mode-switch{background:#f6ede2}:host([theme="editorial"]) .mode-switch button.active{background:#fffaf4}:host([theme="editorial"]) .guest-card{background:#fff3e5;border-color:#ead8c3}',
':host([theme="nocturne"]){--auth-bg:#111a2a;--auth-fg:#f7f9ff;--auth-muted:#b8c3d8;--auth-border:#33425c;--auth-accent:#7e96ff;--auth-accent-2:#a978ff;--auth-soft:#18243a}:host([theme="nocturne"]) .panel{position:relative;overflow:hidden;background:radial-gradient(circle at 50% -10%,rgba(100,126,255,.28),transparent 32%),linear-gradient(180deg,#17233a,#0e1625 72%);border-color:#43526d;box-shadow:0 30px 90px rgba(3,7,18,.55),inset 0 1px 0 rgba(255,255,255,.05)}:host([theme="nocturne"]) .panel:after{content:"";position:absolute;left:-15%;right:-15%;bottom:-42px;height:95px;border-radius:50%;background:radial-gradient(ellipse at center,rgba(103,128,255,.60),rgba(137,77,255,.25) 38%,transparent 70%);filter:blur(8px);pointer-events:none}:host([theme="nocturne"]) .panel>*{position:relative;z-index:1}:host([theme="nocturne"]) .feature{background:linear-gradient(145deg,#6f7fff,#9e69e8);border-color:rgba(255,255,255,.16);color:#fff;box-shadow:0 0 34px rgba(115,126,255,.32)}:host([theme="nocturne"]) .providers{grid-template-columns:1fr}:host([theme="nocturne"]) .provider,:host([theme="nocturne"]) .secondary,:host([theme="nocturne"]) .field input,:host([theme="nocturne"]) .classic-input,:host([theme="nocturne"]) .classic-secondary{background:#1a263a;color:#eef3ff;border-color:#3a4a65}:host([theme="nocturne"]) .provider{justify-content:flex-start;padding:13px 17px}:host([theme="nocturne"]) .provider[data-apple]{background:#f8f9fc;color:#0f1520;border-color:#f8f9fc}:host([theme="nocturne"]) .primary{background:linear-gradient(135deg,#6d86ff,#9367ed);box-shadow:0 11px 28px rgba(93,99,228,.28)}:host([theme="nocturne"]) .mode-switch{background:#172236}:host([theme="nocturne"]) .mode-switch button.active{background:#263550;color:#fff}:host([theme="nocturne"]) .guest-card{background:#18243a;border-color:#34445f}:host([theme="nocturne"]) .divider:before,:host([theme="nocturne"]) .divider:after{background:#344159}:host([theme="nocturne"]) .text-btn{color:#9ab0ff}',
':host([theme="prism"]){--auth-bg:#fff;--auth-fg:#171b3a;--auth-muted:#697093;--auth-border:#dedff3;--auth-accent:#6258e9;--auth-accent-2:#e66cb0;--auth-soft:#f7f3ff}:host([theme="prism"]) .panel{position:relative;overflow:hidden;padding-top:124px;background:radial-gradient(circle at 12% 4%,rgba(98,114,255,.24),transparent 32%),radial-gradient(circle at 92% 15%,rgba(255,125,164,.28),transparent 32%),linear-gradient(180deg,#fbfaff,#fff);border-color:#e3def5;box-shadow:0 28px 78px rgba(84,75,175,.22)}:host([theme="prism"]) .panel:before{content:"";position:absolute;top:18px;left:50%;transform:translateX(-50%);width:220px;height:84px;border-radius:30px;background:radial-gradient(circle at 70% 30%,#ffd290 0 12%,transparent 13%),radial-gradient(circle at 18% 70%,#d1b8ff 0 17%,transparent 18%),radial-gradient(circle at 84% 78%,#ffb2cc 0 14%,transparent 15%),linear-gradient(145deg,#8776ff,#ef9ed2 58%,#8de5da);box-shadow:0 14px 30px rgba(107,83,201,.20)}:host([theme="prism"]) .panel>*{position:relative;z-index:1}:host([theme="prism"]) h2{font-size:31px}:host([theme="prism"]) .providers{grid-template-columns:1fr}:host([theme="prism"]) .provider{justify-content:flex-start;padding:13px 17px;background:rgba(255,255,255,.86);border-color:#e5e0f5;box-shadow:0 7px 18px rgba(92,78,174,.08)}:host([theme="prism"]) .provider[data-apple]{background:#15151b;color:#fff;border-color:#15151b}:host([theme="prism"]) .primary{background:linear-gradient(100deg,#6258e9,#8c66ee 52%,#de6cb1);box-shadow:0 12px 28px rgba(107,81,218,.25)}:host([theme="prism"]) .feature{background:linear-gradient(145deg,#ebe5ff,#dcfbf4);border-color:#dfd9f5;color:#6757dc}:host([theme="prism"]) .guest-card{background:linear-gradient(135deg,#f5f1ff,#effcf9);border-color:#e2dcf4}:host([theme="prism"]) .mode-switch{background:#f3effa}:host([theme="prism"]) .mode-switch button.active{background:#fff}',
'[hidden]{display:none!important}@media(max-width:480px){.panel{padding:20px;border-radius:20px}h2{font-size:25px}.providers{grid-template-columns:1fr}.compact .providers{grid-template-columns:repeat(3,1fr)}}'
].join('');

const esc=s=>String(s||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fields=password=>'<div class="stack"><label class="field"><span class="ico">✉</span><input data-email type="email" autocomplete="email" placeholder="Email address" aria-label="Email address"></label>'+(password?'<label class="field"><span class="ico">⌑</span><input data-password type="password" autocomplete="current-password" placeholder="Password" aria-label="Password"></label>':'')+'</div>';
const head=(title,sub,center)=>'<div class="head'+(center?' center':'')+'"><h2>'+esc(title)+'</h2><p class="sub">'+esc(sub)+'</p></div>';
const GOOGLE_ICON='<svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.4-.18-2.07H12v3.92h5.38a4.6 4.6 0 0 1-2 3.02v2.54h3.24c1.9-1.75 2.98-4.33 2.98-7.41z"/><path fill="#34A853" d="M12 22c2.7 0 4.97-.9 6.62-2.36l-3.24-2.54c-.9.6-2.05.96-3.38.96-2.6 0-4.8-1.76-5.59-4.12H3.06v2.62A10 10 0 0 0 12 22z"/><path fill="#FBBC05" d="M6.41 13.94A6.02 6.02 0 0 1 6.1 12c0-.67.11-1.32.31-1.94V7.44H3.06A10 10 0 0 0 2 12c0 1.61.39 3.13 1.06 4.56l3.35-2.62z"/><path fill="#EA4335" d="M12 5.94c1.47 0 2.8.5 3.84 1.5l2.88-2.88A9.66 9.66 0 0 0 12 2a10 10 0 0 0-8.94 5.44l3.35 2.62C7.2 7.7 9.4 5.94 12 5.94z"/></svg>';
const APPLE_ICON='<svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path fill="currentColor" d="M16.7 12.8c0-2.4 2-3.6 2.1-3.7-1.1-1.7-2.9-1.9-3.6-1.9-1.5-.2-3 .9-3.8.9-.8 0-2-.9-3.3-.8-1.7 0-3.2 1-4.1 2.5-1.8 3-.5 7.5 1.2 10 .8 1.2 1.8 2.5 3.1 2.4 1.2-.1 1.7-.8 3.2-.8s1.9.8 3.2.8c1.3 0 2.2-1.2 3-2.4.9-1.4 1.3-2.7 1.3-2.8-.1 0-2.5-1-2.5-4.2zM14.2 5.6c.7-.9 1.2-2.1 1.1-3.3-1.1 0-2.4.7-3.2 1.6-.7.8-1.3 2-1.1 3.2 1.2.1 2.5-.6 3.2-1.5z"/></svg>';
const PASSKEY_ICON='<svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><circle cx="8" cy="12" r="3.5" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M11.5 12H21m-3 0v3m-3-3v2" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>';

class AppsAuthPanel extends HTMLElement{
  static get observedAttributes(){return['variant','theme','methods','heading','subheading']}
  constructor(){super();this.localMode='sign-in'}
  connectedCallback(){
    if(!this.shadowRoot)this.attachShadow({mode:'open'});
    this.unsubscribe=Auth.onChange(()=>this.render());
    this.render();
  }
  disconnectedCallback(){this.unsubscribe?.()}
  attributeChangedCallback(){if(this.shadowRoot)this.render()}
  get methods(){return new Set((this.getAttribute('methods')||'passkey,emailLink,emailPassword').split(',').map(x=>x.trim()).filter(Boolean))}
  get variant(){return this.getAttribute('variant')||'classic'}
  get theme(){return this.getAttribute('theme')||'airy'}
  has(name){return this.methods.has(name)}
  status(text,error){
    const el=this.shadowRoot.querySelector('[data-status]');
    if(el){el.textContent=text||'';el.className='status'+(error?' error':'')}
  }
  async run(fn,success){
    this.status('Working…');
    try{await fn();this.status(success||'')}catch(e){this.status(e?.message||String(e),true)}
  }
  providers(includePasskey=true){
    const b=[];
    if(this.has('google'))b.push('<button class="provider" data-google>'+GOOGLE_ICON+'<span>Google</span></button>');
    if(this.has('apple'))b.push('<button class="provider" data-apple>'+APPLE_ICON+'<span>Apple</span></button>');
    if(includePasskey&&this.has('passkey'))b.push('<button class="provider" data-passkey>'+PASSKEY_ICON+'<span>Passkey</span></button>');
    return b.length?'<div class="providers">'+b.join('')+'</div>':'';
  }
  bind(){
    const q=s=>this.shadowRoot.querySelector(s);
    const email=()=>q('[data-email]')?.value.trim()||'';
    const password=()=>q('[data-password]')?.value||'';
    q('[data-email-password]')?.addEventListener('click',()=>this.run(()=>Auth.signInEmail(email(),password())));
    q('[data-create-account]')?.addEventListener('click',()=>this.run(()=>Auth.createEmailAccount(email(),password())));
    q('[data-email-link]')?.addEventListener('click',()=>this.run(async()=>{if(!email())throw new Error('Enter your email address.');await Auth.sendEmailLink(email())},'Sign-in link sent.'));
    q('[data-forgot-password]')?.addEventListener('click',()=>this.run(async()=>{if(!email())throw new Error('Enter your email address first.');await Auth.resetPassword(email())},'Password reset email requested.'));
    q('[data-passkey]')?.addEventListener('click',()=>this.run(()=>Auth.signInWithPasskey()));
    q('[data-google]')?.addEventListener('click',()=>this.run(()=>Auth.signInGoogle()));
    q('[data-apple]')?.addEventListener('click',()=>this.run(()=>Auth.signInApple()));
    q('[data-anonymous]')?.addEventListener('click',()=>this.run(()=>Auth.signInAnonymous()));
    q('[data-create-mode]')?.addEventListener('click',()=>{this.localMode='create';this.render()});
    q('[data-signin-mode]')?.addEventListener('click',()=>{this.localMode='sign-in';this.render()});
    q('[data-email-mode]')?.addEventListener('click',()=>{this.localMode='email';this.render()});
    q('[data-back-mode]')?.addEventListener('click',()=>{this.localMode='sign-in';this.render()});
    q('[data-protect]')?.addEventListener('click',()=>{
      const e=q('[data-upgrade-email]')?.value.trim()||'',p=q('[data-upgrade-password]')?.value||'';
      this.run(()=>Auth.upgradeAnonymousWithEmailPassword(e,p));
    });
    q('[data-add-passkey]')?.addEventListener('click',()=>this.run(()=>Auth.registerPasskey('Passkey'),'Passkey added.'));
    q('[data-reset-password]')?.addEventListener('click',()=>this.run(async()=>{const e=Auth.getCurrentUser()?.email;if(!e)throw new Error('This account has no email address.');await Auth.resetPassword(e)},'Password reset email sent.'));
    q('[data-signout]')?.addEventListener('click',()=>this.run(()=>Auth.logout()));
  }
  signedIn(user){
    return '<section class="panel"><div class="identity"><div class="avatar">'+esc((user.displayName||user.email||'U').slice(0,1).toUpperCase())+'</div><div><b>'+esc(user.displayName||user.email||(user.isAnonymous?'Guest account':'Signed in'))+'</b><small>'+(user.isAnonymous?'Guest account · protect it to use on other devices':esc(user.email||user.provider||''))+'</small></div></div>'+
      (user.isAnonymous&&this.has('emailPassword')?'<div class="stack" style="margin-top:14px"><label class="field"><span class="ico">✉</span><input data-upgrade-email type="email" placeholder="Email address"></label><label class="field"><span class="ico">⌑</span><input data-upgrade-password type="password" placeholder="Create password"></label><button class="primary" data-protect>Protect guest account</button></div>':'')+
      '<div class="signed-actions">'+(!user.isAnonymous&&this.has('passkey')?'<button class="secondary" data-add-passkey>Add passkey</button>':'')+(user.email&&this.has('emailPassword')?'<button class="secondary" data-reset-password>Reset password</button>':'')+'<button class="secondary" data-signout>Sign out</button></div><small class="status" data-status></small></section>';
  }
  classic(){
    return '<section class="panel classic-panel"><div class="classic-title"><strong>Sign in</strong></div><div class="classic-row"><input class="classic-input" data-email type="email" autocomplete="email" placeholder="Email"><input class="classic-input" data-password type="password" autocomplete="current-password" placeholder="Password"></div><div class="classic-actions"><button class="classic-primary" data-email-password>Sign in</button><button class="classic-secondary" data-create-account>Create account</button>'+(this.has('emailLink')?'<button class="classic-secondary" data-email-link>Email me a sign-in link</button>':'')+(this.has('emailPassword')?'<button class="classic-secondary" data-forgot-password>Forgot password</button>':'')+(this.has('passkey')?'<button class="classic-secondary" data-passkey>'+PASSKEY_ICON+'<span>Use passkey</span></button>':'')+(this.has('google')?'<button class="classic-secondary" data-google>'+GOOGLE_ICON+'<span>Google</span></button>':'')+(this.has('apple')?'<button class="classic-secondary" data-apple>'+APPLE_ICON+'<span>Apple</span></button>':'')+(this.has('anonymous')?'<button class="classic-secondary" data-anonymous>Continue as guest</button>':'')+'</div><small class="status" data-status></small></section>';
  }
  balanced(title,sub){
    const create=this.localMode==='create';
    return '<section class="panel">'+head(title,sub,false)+'<div class="mode-switch"><button class="'+(!create?'active':'')+'" data-signin-mode>Sign in</button><button class="'+(create?'active':'')+'" data-create-mode>Create account</button></div>'+fields(true)+'<button class="primary" style="margin-top:11px" '+(create?'data-create-account':'data-email-password')+'>'+(create?'Create account':'Continue')+' →</button>'+
      (this.providers()?'<div class="divider">or continue with</div>'+this.providers():'')+
      '<div class="links">'+(this.has('emailLink')?'<button class="text-btn" data-email-link>Email me a sign-in link</button>':'')+(this.has('emailPassword')?'<button class="text-btn" data-forgot-password>Forgot password?</button>':'')+'</div>'+
      (this.has('anonymous')?'<button class="guest-card" data-anonymous><span class="guest-icon">◎</span><span><b>Continue as guest</b><small>Explore now and protect your account later.</small></span></button>':'')+'<small class="status" data-status></small></section>';
  }
  passkeyFirst(title,sub){
    if(this.localMode==='email'){
      return '<section class="panel">'+head(title,sub,true)+fields(true)+'<button class="primary" style="margin-top:11px" data-email-password>Sign in →</button><div class="links"><button class="text-btn" data-back-mode>Back to passkey</button>'+(this.has('emailLink')?'<button class="text-btn" data-email-link>Email link</button>':'')+'</div><small class="status" data-status></small></section>';
    }
    return '<section class="panel"><div class="feature">⌘</div>'+head(title,sub,true)+(this.has('passkey')?'<button class="primary" data-passkey>Use passkey →</button>':'')+'<div class="divider">or</div>'+this.providers(false)+'<div class="links"><button class="text-btn" data-email-mode>Use email instead</button></div>'+(this.has('anonymous')?'<button class="guest-card" data-anonymous><span class="guest-icon">◎</span><span><b>Continue as guest</b><small>No account needed yet.</small></span></button>':'')+'<small class="status" data-status></small></section>';
  }
  magicLink(title,sub){
    return '<section class="panel">'+head(title,sub,true)+'<div class="feature">✉</div>'+fields(false)+'<button class="primary" style="margin-top:11px" data-email-link>Send secure sign-in link →</button><p class="magic-note">No password to remember. Open the link on this device to continue.</p><details class="more"><summary>Other ways to sign in</summary><div class="alt-list">'+(this.has('passkey')?'<button class="secondary" data-passkey>Use passkey</button>':'')+(this.has('google')?'<button class="secondary" data-google>Continue with Google</button>':'')+(this.has('apple')?'<button class="secondary" data-apple>Continue with Apple</button>':'')+'</div></details>'+(this.has('anonymous')?'<div class="links"><button class="text-btn" data-anonymous>Continue as guest</button></div>':'')+'<small class="status" data-status></small></section>';
  }
  guestFirst(title,sub){
    return '<section class="panel">'+head(title,sub,true)+'<div class="feature">◎</div>'+(this.has('anonymous')?'<button class="primary" data-anonymous>Start now as guest →</button>':'')+'<div class="benefits"><div class="benefit"><span class="tick">✓</span><span>No sign-up required to start</span></div><div class="benefit"><span class="tick">✓</span><span>Your progress stays on this device</span></div><div class="benefit"><span class="tick">✓</span><span>Protect the account later without losing progress</span></div></div><div class="divider">already have an account?</div><div class="alt-list">'+(this.has('passkey')?'<button class="secondary" data-passkey>Use passkey</button>':'')+'<button class="secondary" data-email-mode>Email sign in</button></div>'+(this.localMode==='email'?'<div style="margin-top:12px">'+fields(true)+'<button class="primary" style="margin-top:10px" data-email-password>Sign in</button></div>':'')+'<small class="status" data-status></small></section>';
  }
  compact(title,sub){
    return '<section class="panel compact">'+head(title,sub,false)+fields(true)+'<button class="primary" style="margin-top:10px" data-email-password>Sign in →</button><div class="divider">or</div>'+this.providers()+'<details class="more" '+(this.localMode==='create'?'open':'')+'><summary>More options</summary><div class="links">'+(this.has('emailLink')?'<button class="text-btn" data-email-link>Email link</button>':'')+(this.has('emailPassword')?'<button class="text-btn" data-forgot-password>Forgot password</button>':'')+(this.has('anonymous')?'<button class="text-btn" data-anonymous>Continue as guest</button>':'')+'<button class="text-btn" data-create-mode>Create account</button></div>'+(this.localMode==='create'?'<div style="margin-top:10px">'+fields(true)+'<button class="primary" style="margin-top:10px" data-create-account>Create account</button></div>':'')+'</details><small class="status" data-status></small></section>';
  }
  render(){
    const snap=Auth.snapshot(),user=snap.user,v=this.variant;
    const title=this.getAttribute('heading')||(v==='guest-first'?'Start exploring':v==='magic-link'?'Sign in with a link':v==='passkey-first'?'Welcome back':v==='compact'?'Sign in':'Shared account');
    const sub=this.getAttribute('subheading')||(v==='guest-first'?'Try the app first. Create an account only when you need one.':v==='magic-link'?'We will email you a secure link. No password required.':v==='passkey-first'?'Use Face ID, Touch ID or your device passkey for the quickest route in.':v==='compact'?'Pick up where you left off.':'Save your progress and access it from any device.');
    const body=user?this.signedIn(user):v==='classic'?this.classic():v==='passkey-first'?this.passkeyFirst(title,sub):v==='magic-link'?this.magicLink(title,sub):v==='guest-first'?this.guestFirst(title,sub):v==='compact'?this.compact(title,sub):this.balanced(title,sub);
    this.shadowRoot.innerHTML='<style>'+CSS+'</style>'+body;
    this.bind();
  }
}
if(!customElements.get('apps-auth-panel'))customElements.define('apps-auth-panel',AppsAuthPanel);
export { AppsAuthPanel };
