const STYLE_ID='apps-shared-notes-style-v1';
const cssUrl=new URL('./styles.css',import.meta.url).href;
function ensureStyles(){if(document.getElementById(STYLE_ID))return;const l=document.createElement('link');l.id=STYLE_ID;l.rel='stylesheet';l.href=cssUrl;document.head.appendChild(l)}
const q=(root,s)=>root.querySelector(s),qa=(root,s)=>[...root.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function labelFor(el){return el?.dataset?.noteLabel||el?.getAttribute?.('aria-label')||el?.querySelector?.('h1,h2,h3')?.textContent?.trim()||el?.textContent?.trim()?.replace(/\s+/g,' ').slice(0,90)||'App element'}
function pathFor(el){
  if(!el||el===document.body)return 'page:general';if(el.dataset.noteAnchor)return el.dataset.noteAnchor;if(el.id)return `id:${el.id}`;
  const section=el.closest('[data-note-anchor],[id],main,section,article,nav,header,footer');if(section&&section!==el){if(section.dataset.noteAnchor)return section.dataset.noteAnchor;if(section.id)return `id:${section.id}`}
  const name=(el.tagName||'element').toLowerCase(), siblings=el.parentElement?[...el.parentElement.children].filter(x=>x.tagName===el.tagName):[],i=Math.max(0,siblings.indexOf(el));return `auto:${name}:${i}`;
}
function selectedText(){return String(globalThis.getSelection?.()?.toString?.()||'').trim().slice(0,1000)}
export async function mountNotesUI(notes,options={}){
  ensureStyles();
  const cfg={launcher:true,launcherLabel:'＋ Note',annotation:true,showTypes:true,...options};let annotating=false,editingId=null,context=null,filter='open';
  const launcher=document.createElement('button');launcher.type='button';launcher.className='apps-notes-launcher';launcher.textContent=cfg.launcherLabel;launcher.setAttribute('aria-label','Open notes and annotations');if(cfg.launcher!==false)document.body.appendChild(launcher);
  const banner=document.createElement('div');banner.className='apps-notes-annotation-banner';banner.hidden=true;banner.innerHTML='<span>Tap a highlighted area to attach a note.</span><button type="button">Done</button>';document.body.appendChild(banner);
  const dialog=document.createElement('dialog');dialog.className='apps-notes-dialog';dialog.innerHTML=`<div class="apps-notes-shell"><header><div><p class="eyebrow">NOTES & ANNOTATIONS</p><h2>${esc(cfg.title||'Notes for review')}</h2></div><button class="icon-close" data-close aria-label="Close">×</button></header><div class="toolbar"><button class="primary" data-new>＋ General note</button>${cfg.annotation!==false?'<button data-select>⌖ Select an element</button>':''}<button data-copy>Copy review pack</button><button data-publish hidden>Refresh review feed</button></div><section class="composer" hidden><div class="context"><strong data-context-label>General note</strong><span data-context-id>page:general</span></div><blockquote data-quote hidden></blockquote><textarea rows="5" maxlength="6000" placeholder="What should change, what was confusing, or what should be remembered?"></textarea><div class="composer-options">${cfg.showTypes!==false?'<label>Type <select data-type><option value="developer">Developer note</option><option value="feedback">Feedback</option><option value="annotation">Annotation</option></select></label>':''}<label><input type="checkbox" data-review checked> Include in review queue</label></div><div class="composer-actions"><button data-cancel>Cancel</button><button class="primary" data-save>Save note</button></div></section><details open><summary>Notes history</summary><div class="filters"><button data-filter="open" class="active">Open</button><button data-filter="review">For review</button><button data-filter="implemented">Implemented</button><button data-filter="all">All</button></div><div class="list"></div></details><footer><span data-status></span></footer></div>`;document.body.appendChild(dialog);
  if(typeof notes.config.transport.publishReviewFeed==='function')q(dialog,'[data-publish]').hidden=false;
  function ctxFrom(el){const anchorId=pathFor(el);return{anchorId,anchorLabel:labelFor(el),selector:el?.id?`#${CSS.escape(el.id)}`:'',selectedText:selectedText(),elementText:el?.textContent?.trim()?.replace(/\s+/g,' ').slice(0,1000)||''}}
  function openComposer(ctx={anchorId:'page:general',anchorLabel:'General page note'},note=null){context=ctx;editingId=note?.id||null;q(dialog,'.composer').hidden=false;q(dialog,'[data-context-label]').textContent=ctx.anchorLabel||'General note';q(dialog,'[data-context-id]').textContent=ctx.anchorId||'page:general';const quote=q(dialog,'[data-quote]');quote.hidden=!ctx.selectedText;quote.textContent=ctx.selectedText?`“${ctx.selectedText}”`:'';q(dialog,'textarea').value=note?.text||'';q(dialog,'[data-review]').checked=note?.reviewRequired!==false;const type=q(dialog,'[data-type]');if(type)type.value=note?.type||notes.config.defaultType||'developer';q(dialog,'[data-save]').textContent=note?'Save changes':'Save note';notes.saveDraft({noteId:editingId,text:q(dialog,'textarea').value,context,type:type?.value||notes.config.defaultType}).catch(()=>{});setTimeout(()=>q(dialog,'textarea').focus(),10)}
  function closeComposer(){editingId=null;context=null;q(dialog,'.composer').hidden=true;q(dialog,'textarea').value='';notes.clearDraft().catch(()=>{})}
  function listForFilter(){if(filter==='open')return notes.list({open:true});if(filter==='review')return notes.list({review:true});if(filter==='implemented')return notes.list({status:'implemented'});return notes.list()}
  function render(){const host=q(dialog,'.list'),list=listForFilter();host.innerHTML=list.length?list.map(n=>`<article data-id="${esc(n.id)}" class="${n.status==='implemented'?'implemented':''}"><div class="note-head"><strong>${esc(n.anchorLabel||'General note')}</strong><span class="type">${esc(n.type)}</span></div><p>${esc(n.text)}</p>${n.selectedText?`<blockquote>“${esc(n.selectedText)}”</blockquote>`:''}<small>${esc(n.appVersion||'')} · ${new Date(n.updatedAt).toLocaleString('en-GB')} · ${esc(n.status)}</small>${n.status==='implemented'&&n.implementationVersion?`<p class="implemented-note">✓ Implemented in ${esc(n.implementationVersion)}${n.implementationMessage?' — '+esc(n.implementationMessage):''}</p>`:''}<div class="actions"><button data-action="goto">Go to</button><button data-action="edit">Edit</button>${n.status==='implemented'?'<button data-action="restore">Reopen</button>':`<button data-action="review">${n.reviewRequired?'Remove from review':'Add to review'}</button><button data-action="archive">Archive</button>`}</div></article>`).join(''):'<div class="empty">No notes in this view yet.</div>';renderPins()}
  function renderPins(){document.querySelectorAll('.apps-note-pin').forEach(x=>x.remove());document.querySelectorAll('.apps-has-notes').forEach(x=>x.classList.remove('apps-has-notes'));const counts=new Map();notes.list({open:true}).forEach(n=>counts.set(n.anchorId,(counts.get(n.anchorId)||0)+1));document.querySelectorAll('[data-note-anchor],[id]').forEach(el=>{const id=pathFor(el),count=counts.get(id)||0;if(!count||['BUTTON','INPUT','SELECT','TEXTAREA','DIALOG'].includes(el.tagName)||el.closest('.apps-notes-dialog'))return;el.classList.add('apps-has-notes');const pin=document.createElement('button');pin.type='button';pin.className='apps-note-pin';pin.textContent=count;pin.title=`${count} open note${count===1?'':'s'}`;pin.onclick=e=>{e.preventDefault();e.stopPropagation();open();filter='all';updateFilters();render()};el.appendChild(pin)})}
  function updateFilters(){qa(dialog,'[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
  function open(){render();if(!dialog.open)dialog.showModal()}
  function toggleAnnotation(value){annotating=typeof value==='boolean'?value:!annotating;document.body.classList.toggle('apps-annotating',annotating);banner.hidden=!annotating}
  launcher.onclick=open;q(dialog,'[data-close]').onclick=()=>dialog.close();q(dialog,'[data-new]').onclick=()=>openComposer();q(dialog,'[data-select]')?.addEventListener('click',()=>{dialog.close();toggleAnnotation(true)});q(dialog,'[data-cancel]').onclick=closeComposer;banner.querySelector('button').onclick=()=>toggleAnnotation(false);
  q(dialog,'textarea').oninput=()=>{const type=q(dialog,'[data-type]');notes.saveDraft({noteId:editingId,text:q(dialog,'textarea').value,context,type:type?.value||notes.config.defaultType}).catch(()=>{})};
  q(dialog,'[data-save]').onclick=async()=>{const text=q(dialog,'textarea').value.trim();if(!text)return q(dialog,'textarea').focus();const existing=editingId?notes.list().find(n=>n.id===editingId):null;await notes.upsert({...existing,id:editingId||undefined,text,...(context||{}),type:q(dialog,'[data-type]')?.value||notes.config.defaultType,reviewRequired:q(dialog,'[data-review]').checked});closeComposer();render()};
  q(dialog,'[data-copy]').onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(notes.reviewPack(),null,2));q(dialog,'[data-status]').textContent='Review pack copied.'};
  q(dialog,'[data-publish]').onclick=async()=>{const r=await notes.publishReviewFeed(true);q(dialog,'[data-status]').textContent=r?.status==='unavailable'?'Review feed is not configured.':'Review feed refreshed.'};
  q(dialog,'.filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;updateFilters();render()};
  q(dialog,'.list').onclick=async e=>{const b=e.target.closest('[data-action]'),card=e.target.closest('[data-id]');if(!b||!card)return;const n=notes.list().find(x=>x.id===card.dataset.id);if(!n)return;if(b.dataset.action==='edit')openComposer(n,n);if(b.dataset.action==='archive'){await notes.archive(n.id);render()}if(b.dataset.action==='restore'){await notes.restore(n.id);render()}if(b.dataset.action==='review'){await notes.upsert({...n,reviewRequired:!n.reviewRequired});render()}if(b.dataset.action==='goto'){dialog.close();const el=n.selector?document.querySelector(n.selector):[...document.querySelectorAll('[data-note-anchor],[id]')].find(x=>pathFor(x)===n.anchorId);el?.scrollIntoView({behavior:'smooth',block:'center'});el?.classList.add('apps-note-flash');setTimeout(()=>el?.classList.remove('apps-note-flash'),1500)}};
  dialog.addEventListener('cancel',e=>{e.preventDefault();dialog.close()});
  document.addEventListener('click',e=>{if(!annotating||e.target.closest('.apps-notes-dialog,.apps-notes-annotation-banner,.apps-notes-launcher'))return;const el=e.target.closest('[data-note-anchor],[id],section,article,main,nav,header,footer');if(!el)return;e.preventDefault();e.stopPropagation();toggleAnnotation(false);open();openComposer(ctxFrom(el))},true);
  const unsub=notes.subscribe(()=>render());
  const draft=await notes.getDraft().catch(()=>null);if(draft?.text){open();openComposer(draft.context||undefined,draft.noteId?notes.list().find(n=>n.id===draft.noteId):null);q(dialog,'textarea').value=draft.text}
  renderPins();
  return {open,toggleAnnotation,render,destroy(){unsub();launcher.remove();banner.remove();dialog.remove();document.body.classList.remove('apps-annotating')}};
}
